<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Version>1.0.0-beta.1</Version>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Buildalyzer" Version="8.0.0" />
    <PackageReference Include="Buildalyzer.Workspaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Csharp" Version="5.3.0" />
    <PackageReference Include="Neo4j.Driver" Version="6.0.0" />
    <PackageReference Include="Spectre.Console" Version="0.55.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.5" />
  </ItemGroup>

</Project>